import { fetch as expoFetch } from 'expo/fetch'
import { request, jsonBody, getToken, API_BASE, notifyUnauthorized, type ApiError } from './client'

export interface Pool { name: string; document_count: number }
export interface Doc {
  key: string
  file_name: string
  pool: string
  pool_assigned: boolean
  chunk_count: number
  processed_at: string
  // Generated by a background LLM pass shortly after ingestion completes —
  // blank until then, or if the LLM is disabled (task.md §1d).
  summary: string
}

// Kept in sync with backend/main.py ALLOWED_EXTENSIONS — images are OCR'd via
// the vision model at ingestion, so they go through the same /upload route.
export const IMAGE_MIME_TYPES = ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/bmp', 'image/tiff']
export const DOCUMENT_MIME_TYPES = [
  'application/pdf', 'text/*', 'application/json', 'application/xml', 'text/xml',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
]

export const fetchPools = () => request<{ pools: Pool[]; total: number }>('/pools')
export const createPool = (name: string) => request<{ status: string; pool: string }>('/pools', jsonBody('POST', { name }))
export const deletePool = (name: string) => request(`/pools/${encodeURIComponent(name)}`, { method: 'DELETE' })

export const fetchDocuments = () => request<{ documents: Doc[]; total: number }>('/documents')

export const deleteDocument = (fileName: string, pool: string) =>
  request(`/documents/${encodeURIComponent(fileName)}?pool=${encodeURIComponent(pool)}`, { method: 'DELETE' })

export const moveDocument = (fileName: string, currentPool: string, newPool: string) =>
  request(`/documents/${encodeURIComponent(fileName)}/pool`, jsonBody('PATCH', { current_pool: currentPool, new_pool: newPool }))

export interface GraphNode { id: string; label: string; source_count: number }
export interface GraphEdge { source: string; target: string; label: string }
export interface PoolGraph { nodes: GraphNode[]; edges: GraphEdge[] }

// Knowledge graph for a pool. Pro+ only — a Free-tier account gets 403.
export const fetchPoolGraph = (pool: string) =>
  request<PoolGraph>(`/pools/${encodeURIComponent(pool)}/graph`)

// One merged graph across every pool. Concepts aren't pool-specific, and the
// per-pool view hid a document uploaded to another pool — mobile shows this
// unified view instead, with no pool selector.
export const fetchUserGraph = () => request<PoolGraph>('/graph')

export interface PickedFile { uri: string; name: string; mimeType?: string }

export interface UploadStartResult {
  status: string
  task_id: string
  filename: string
  pool: string
  pool_assigned: boolean
  message: string
}

/**
 * POST the file to /upload, reporting byte-transfer progress as a 0..1
 * fraction via ``onTransfer``.
 *
 * Uses XMLHttpRequest rather than fetch because only XHR exposes
 * ``upload.onprogress`` — with fetch, an 11 MB file produced a multi-second
 * dead stretch where the UI showed nothing at all and looked hung. Handles
 * 401 through ``notifyUnauthorized`` so bypassing ``request`` doesn't also
 * bypass the app-wide auto-logout.
 */
export async function uploadDocument(
  file: PickedFile, pool = '', chunkSize = 512, chunkOverlap = 50,
  onTransfer?: (fraction: number) => void,
) {
  const token = await getToken()
  const form = new FormData()
  // React Native FormData file shape.
  form.append('file', { uri: file.uri, name: file.name, type: file.mimeType || 'application/octet-stream' } as any)
  form.append('pool', pool)
  form.append('chunk_size', String(chunkSize))
  form.append('chunk_overlap', String(chunkOverlap))

  return new Promise<UploadStartResult>((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open('POST', `${API_BASE}/upload`)
    if (token) xhr.setRequestHeader('Authorization', `Bearer ${token}`)

    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable && e.total > 0) onTransfer?.(e.loaded / e.total)
    }
    xhr.onload = () => {
      let body: any
      try { body = JSON.parse(xhr.responseText) } catch { body = null }
      if (xhr.status >= 200 && xhr.status < 300) {
        resolve(body as UploadStartResult)
        return
      }
      if (xhr.status === 401) notifyUnauthorized()
      const err: ApiError = new Error(body?.detail || body?.message || `HTTP ${xhr.status}`)
      err.status = xhr.status
      reject(err)
    }
    xhr.onerror = () => reject(new Error('Upload failed — check your connection and try again.'))
    xhr.ontimeout = () => reject(new Error('Upload timed out. Please try again.'))
    xhr.send(form)
  })
}

export interface UploadProgressEvent { progress: number; message: string; status: 'processing' | 'complete' | 'failed' }
export interface UploadProgressHandlers {
  onProgress?: (p: UploadProgressEvent) => void
  onDone?: (p: UploadProgressEvent) => void
  onError?: (e: Error) => void
}

// Blank-line SSE frame separator, tolerant of \r\n / \r / \n line endings —
// same tolerant split used for /query/stream (sse_starlette uses \r\n).
const FRAME_SEP = /\r\n\r\n|\r\r|\n\n/

/**
 * Subscribes to GET /progress/{task_id}, an SSE stream (no plain-JSON polling
 * endpoint exists server-side). Mirrors the approach used by streamQuery in
 * api/query.ts, since RN has no native EventSource.
 *
 * Uses `expo/fetch`, NOT React Native's global fetch: RN's fetch never
 * exposes a readable `body.getReader()`, so this used to fall straight into
 * the no-reader branch below and report an instant fake "complete" — the
 * progress bar never moved during processing, which is exactly what made a
 * large upload look hung. Same root cause as the chat-streaming fix in
 * api/query.ts (task.md P1 #8).
 */
export async function watchUploadProgress(taskId: string, h: UploadProgressHandlers) {
  try {
    const token = await getToken()
    const res = await expoFetch(`${API_BASE}/progress/${encodeURIComponent(taskId)}`, {
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
    const reader = (res as any).body?.getReader?.()
    if (!reader) {
      h.onDone?.({ progress: 100, message: 'Done — ready to search', status: 'complete' })
      return
    }
    const decoder = new TextDecoder()
    let buffer = ''
    while (true) {
      const { value, done } = await reader.read()
      if (done) break
      buffer += decoder.decode(value, { stream: true })
      let m
      while ((m = FRAME_SEP.exec(buffer)) !== null) {
        const stop = dispatchProgress(buffer.slice(0, m.index), h)
        buffer = buffer.slice(m.index + m[0].length)
        if (stop) return
      }
    }
  } catch (e: any) {
    h.onError?.(e)
  }
}

function dispatchProgress(frame: string, h: UploadProgressHandlers): boolean {
  let event = 'message'
  const dataLines: string[] = []
  for (const line of frame.split(/\r\n|\r|\n/)) {
    if (line.startsWith('event:')) event = line.slice(6).trim()
    else if (line.startsWith('data:')) dataLines.push(line.slice(5).replace(/^ /, ''))
  }
  if (!dataLines.length) return false
  let data: any
  try { data = JSON.parse(dataLines.join('\n')) } catch { return false }
  if (event === 'progress') { h.onProgress?.(data); return false }
  if (event === 'complete') { h.onDone?.(data); return true }
  if (event === 'error') { h.onError?.(new Error(data?.detail || 'progress stream error')); return true }
  return false
}

// An upload has two phases the user shouldn't have to think about: sending
// the bytes, then the server ingesting them. Each is mapped onto half of one
// bar so it only ever moves forwards -- reporting both as 0..100 made the bar
// visibly jump backwards to 0 when the second phase started.
const TRANSFER_SHARE = 0.5

export async function uploadWithProgress(
  file: PickedFile, pool: string, handlers: UploadProgressHandlers, chunkSize = 512, chunkOverlap = 50,
) {
  const res = await uploadDocument(file, pool, chunkSize, chunkOverlap, (fraction) => {
    handlers.onProgress?.({
      progress: Math.round(fraction * 100 * TRANSFER_SHARE),
      message: fraction >= 1 ? 'Uploaded — starting processing…' : 'Uploading…',
      status: 'processing',
    })
  })
  if (!res.task_id) {
    handlers.onDone?.({ progress: 100, message: 'Done — ready to search', status: 'complete' })
    return res
  }
  await watchUploadProgress(res.task_id, {
    ...handlers,
    onProgress: (p) => handlers.onProgress?.({
      ...p,
      progress: Math.round(100 * TRANSFER_SHARE + p.progress * (1 - TRANSFER_SHARE)),
    }),
  })
  return res
}
